name: Publish Package
on:
  release:
    types:
      - published
job:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instal Poetry
        run: pip install --upgrade pip && pip install poetry
      - name: Publish to PyPI
        run: poetry publish --build -u '__token__' -p '${{ secrets.PYPI_API_TOKEN }}'
